CREATE TABLE User (
    idUser SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail VARCHAR(40) NOT NULL,
    password VARCHAR(100) NOT NULL,
    lastname VARCHAR(40) NOT NULL,
    firstname VARCHAR(40) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Post (
    idPost SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user SMALLINT UNSIGNED NOT NULL,
    article TEXT,
    nbLikes SMALLINT DEFAULT 0,
    nbDislikes SMALLINT DEFAULT 0,
    date_creation TIMESTAMP NOT NULL,
    FOREIGN KEY (user) REFERENCES User(idUser)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Comment (
    idComment SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user SMALLINT UNSIGNED NOT NULL,
    post SMALLINT UNSIGNED NOT NULL,
    commentaire TEXT,
    FOREIGN KEY (user) REFERENCES User(idUser),
    FOREIGN KEY (post) REFERENCES Post(idPost)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Likes (
    idLike SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user SMALLINT UNSIGNED NOT NULL,
    post SMALLINT UNSIGNED NOT NULL,
    isLike SMALLINT NOT NULL,
    FOREIGN KEY (user) REFERENCES User(idUser),
    FOREIGN KEY (post) REFERENCES Post(idPost)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

INSERT INTO User (mail, lastname, firstname, password, isAdmin) VALUES ('admin@admin.fr','admin','admin','$2b$10$TwjVHQ2XXrq7QGnC0NW4bug170v/tCwOsy.qAEd1zYISUfkKHPduu',TRUE);